apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-nginx-config
  namespace: {{ .Values.namespace }}
data:
  nginx.conf: |  
    server {
      listen 80;
      server_name _;
  
      root /public_html;
  
      location / {
        index index.php index.html;
      }
  
      location ~* \.php$ {
        fastcgi_pass {{ .Values.php.serviceName }}:{{ .Values.php.port }};
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
      }
    }