apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.web.serviceName }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.web.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.web.serviceName }}
  template:
    metadata:
      labels:
        app: {{ .Values.web.serviceName }}
        version: {{ .Values.web.image.tag }}
        web: linux101
    spec:
      containers:
        - name: {{ .Values.web.serviceName }}
          image: "{{ .Values.web.image.repository }}:{{ .Values.web.image.tag }}"
          imagePullPolicy: IfNotPresent
          env:
            - name: VERSION
              value: "{{ .Values.web.image.tag }}"
          livenessProbe:
            exec:
              command: {{ .Values.web.livenessProbe.execCommand | toJson }}
            failureThreshold: {{ .Values.web.livenessProbe.failureThreshold }}
            periodSeconds: {{ .Values.web.livenessProbe.periodSeconds }}
            successThreshold: {{ .Values.web.livenessProbe.successThreshold }}
            timeoutSeconds: {{ .Values.web.livenessProbe.timeoutSeconds }}
          ports:
            - containerPort: {{ .Values.web.port }}
              protocol: TCP
          volumeMounts:
          - name: nginx-config
            mountPath: /etc/nginx/conf.d/default.conf
            subPath: nginx.conf
      volumes:
      - name: nginx-config
        configMap:
          name: {{ .Release.Name }}-nginx-config 