apiVersion: v1
kind: Service
metadata:
  name: linux101-php
spec:
  ports:
    - port: {{ .Values.php.port }}
      targetPort: {{ .Values.php.port }}
  selector:
    app: linux101-php
  type: ClusterIP