apiVersion: v1
kind: Service
metadata:
  name: linux101-web
spec:
  ports:
    - port: {{ .Values.web.port }}
      targetPort: {{ .Values.web.port }}
  selector:
    app: linux101-web
  type: ClusterIP