apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.php.serviceName }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - port: {{ .Values.php.port }}
      targetPort: {{ .Values.php.port }}
  selector:
    app: {{ .Values.php.serviceName }}
  type: ClusterIP