
php:
  port: 9000
  livenessProbe:
    tcpSocketPort: 9000
    initialDelaySeconds: 5
    periodSeconds: 10
    failureThreshold: 3
    successThreshold: 1
    timeoutSeconds: 1
    service:
      port: 9000

web:
  port: 80