
php:
  port: 9000
  livenessProbe:
    tcpSocketPort: 9000
    initialDelaySeconds: 5
    periodSeconds: 10
    failureThreshold: 3
    successThreshold: 1
    timeoutSeconds: 1
    service:
      port: 9000

web:
  port: 80

ingress:
  enabled: true
  ingressClassName: "nginx"
  rewriteTarget: /
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  hosts:
    - host: "linux102.felipeeduribeiro.com.br"
      paths:
        - path: /
          pathType: Prefix
          service: my-service
          port: 80
  tls:
    enabled: false
    config:
      - hosts:
          - "example.com"
        secretName: my-tls-secret
