namespace: "dev"
env: "dev"
php:
  replicaCount: 1
  image:
    repository: feliperibeiro95/linux101-php
    tag: "1.5.6"
  serviceName: linux101-php-dev

web:
  replicaCount: 1
  image:
    repository: feliperibeiro95/linux101-web
    tag: "1.5.6"
  serviceName: linux101-web-dev
  livenessProbe:
    execCommand: 
      - wget
      - -T2
      - -O-
      - linux101-web-dev:80
    failureThreshold: 3
    periodSeconds: 60
    successThreshold: 1
    timeoutSeconds: 1

hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50