namespace: "dev"
env: "dev"
php:
  replicaCount: 1
  image:
    repository: feliperibeiro95/linux101-php
    tag: "latest"
  serviceName: linux101-php-dev

web:
  replicaCount: 1
  image:
    repository: feliperibeiro95/linux101-web
    tag: "latest"
  serviceName: linux101-web-dev
  livenessProbe:
    execCommand: 
      - wget
      - -T2
      - -O-
      - linux101-web-dev:8080
    failureThreshold: 3
    periodSeconds: 60
    successThreshold: 1
    timeoutSeconds: 1

hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50

ingress:
  enabled: true
  ingressClassName: "nginx"
  rewriteTarget: /
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  hosts:
    - host: "linux102-dev.felipeduribeiro.com.br"
      paths:
        - path: /
          pathType: Prefix
          service: linux101-web-dev
          port: 8080
  tls:
    enabled: true
    config:
      - hosts:
          - "linux102-dev.felipeduribeiro.com.br"
        secretName: linux102-dev-cert
