namespace: "linux101"
php:
  replicaCount: 1
  image:
    repository: feliperibeiro95/linux101-php
    tag: "1.5.7"
  serviceName: linux101-php

web:
  replicaCount: 1
  image:
    repository: feliperibeiro95/linux101-web
    tag: "1.5.7"
  serviceName: linux101-web
  livenessProbe:
    execCommand: 
      - wget
      - -T2
      - -O-
      - linux101-web:80
    failureThreshold: 3
    periodSeconds: 60
    successThreshold: 1
    timeoutSeconds: 1

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50

ingress:
  enabled: true
  ingressClassName: "nginx"
  rewriteTarget: /
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  hosts:
    - host: "linux102.felipeduribeiro.com.br"
      paths:
        - path: /
          pathType: Prefix
          service: linux101-web
          port: 80
  tls:
    enabled: true
    config:
      - hosts:
          - "linux102.felipeduribeiro.com.br"
        secretName: linux102-cert