name: CI/CD Pipeline

on:
  release:
    types:
      - published  # Aciona quando um release é publicado

jobs:
  check-tag:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag-check.outputs.tag }}
    steps:
      # Etapa para fazer o checkout do código
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Garante que todo o histórico de commits e tags seja recuperado
          submodules: true  # Inclui submódulos, se houver no repositório

      # Etapa para verificar se a tag foi encontrada
      - name: Check for tag
        id: tag-check
        run: |
          TAG_NAME=${{ github.event.release.tag_name }}
          if [ -z "$TAG_NAME" ]; then
            echo "::error::No tag found on this commit."
            exit 1
          fi
          echo "tag=$TAG_NAME" >> $GITHUB_OUTPUT

  build-and-push:
    needs: check-tag
    runs-on: ubuntu-latest
    steps:
      # Checkout do código (novamente, caso o primeiro job não tenha sido suficiente)
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true

      # Configura Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Loga no Docker Hub
      - name: Log in to DockerHub
        uses: docker/login-action@v1
        with:
          username: feliperibeiro95
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Copy Files
        run: |
          cp -rp public_html/ linux101-php/
          cp -rp public_html/ linux101-web/

      # Build e push da imagem Docker
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: feliperibeiro95/linux101-web:latest,feliperibeiro95/linux101-web:${{ needs.check-tag.outputs.tag }}
          context: ./linux101-web
          platforms: linux/amd64,linux/arm64

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: feliperibeiro95/linux101-php:latest,feliperibeiro95/linux101-php:${{ needs.check-tag.outputs.tag }}
          context: ./linux101-php
          platforms: linux/amd64,linux/arm64