name: CI/CD Pipeline

on:
  release:
    types:
      - published  # Aciona quando um release é publicado

jobs:
  check-tag:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag-check.outputs.tag }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Garante que o repositório seja clonado com todas as tags e histórico
      
      - name: Check for tag
        id: tag-check
        run: |
          TAG_NAME=${{ github.event.release.tag_name }}
          if [ -z "$TAG_NAME" ]; then
            echo "::error::No tag found on this commit."
            exit 1
          fi
          echo "tag=$TAG_NAME" >> $GITHUB_OUTPUT
          
  build-and-push:
    needs: check-tag
    runs-on: ubuntu-latest
    steps:
      # Debug: Verifique a estrutura de diretórios
      - name: Show current directory
        run: pwd  # Mostra o diretório de trabalho atual
      
      - name: List directory contents
        run: ls -l  # Exibe o conteúdo do diretório atual
      
      - name: Show directory structure
        run: tree  # Exibe a estrutura de diretórios

      # Configura o Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Logando no DockerHub com seu nome de usuário e senha diretamente (não use secrets se não for necessário)
      - name: Log in to DockerHub
        uses: docker/login-action@v1
        with:
          username: feliperibeiro95  # Aqui você usa o nome de usuário fixo
          password: ${{ secrets.DOCKER_PASSWORD }}  # Se desejar continuar usando secret para a senha

      # Mostra o nome da release para verificar
      - name: Show release name
        run: echo "feliperibeiro95/linux101-web:${{ needs.check-tag.outputs.tag }}"

      # Construção e envio para o Docker Hub
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: feliperibeiro95/linux101-web:${{ needs.check-tag.outputs.tag }}
          context: ./linux101-web
          platforms: linux/amd64,linux/arm64
